### ISSUE TITLE
Add a photo?

### ISSUE THREAD

**Issue by aioue** [rgravlin/pyportal-temperature-monitor#1]
Interested in this project. Any chance you could add an image of what it looks like please?

**Comment by rgravlin** [comment]
Absolutely.  I'll put something together today hopefully that will show the visual representation of the PyPortal on the different temperature increments.

If it would be of interest, I have another project that is currently private that I would have no problem making public, which is the back-end part of this project.  It uses a Feather S2 w/ BME280 temperature sensor to collect data to publish to local InfluxDB server which the PyPortal (this project) uses to query.  If this would be of interest let me know and I would be happy to publish it and link it up here.

Thanks for the interest!

**Comment by aioue** [comment]
Thank you. More source is more better 😉 Someone will find the sensor backend useful.

**Comment by rgravlin** [comment]
Let me know if this is what you were looking for:
https://github.com/rgravlin/pyportal-temperature-monitor/pull/2

**Comment by aioue** [comment]
Yes, that's it! Thank you.

**Comment by rgravlin** [comment]
Awesome this has been resolved with https://github.com/rgravlin/pyportal-temperature-monitor/pull/2
